[project]
name = "ai-powered-sales-intelligence-platform"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[project.scripts]
ai-powered-sales-intelligence-platform = "ai_powered_sales_intelligence_platform:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
