"""
Guarded SQL Tools for Agentic execution.

Validates all generated SQL through `sql_guard`, executes queries safely against MySQL,
and tracks provenance metadata (rows, latency, query strings).
"""

import time
from typing import Any

from sqlalchemy import text

from ml.common.db import get_engine
from src.provenance.tracker import ProvenanceTracker
from src.security.sql_guard import SQLSecurityError, sql_guard


def execute_analytical_sql(
    query: str,
    tracker: ProvenanceTracker | None = None,
) -> dict[str, Any]:
    """
    Validates, sanitizes, and executes read-only SQL queries against the data warehouse.

    Args:
        query: SQL query generated by Text-to-SQL agent.
        tracker: Optional ProvenanceTracker to log execution.

    Returns:
        Dict with status, row_count, columns, data, execution_time_ms, or error.
    """
    start_time = time.perf_counter()
    try:
        # 1. Validate & sanitize query through firewall
        sanitized_query = sql_guard.validate_and_sanitize(query)

        # 2. Execute query
        engine = get_engine()
        with engine.connect() as conn:
            result = conn.execute(text(sanitized_query))
            columns = list(result.keys())
            rows = [dict(zip(columns, row)) for row in result.fetchall()]

        latency_ms = (time.perf_counter() - start_time) * 1000.0

        # Convert non-serializable objects (decimals, dates) to standard types
        serializable_rows = []
        for r in rows:
            clean_r = {}
            for k, v in r.items():
                if hasattr(v, "isoformat"):
                    clean_r[k] = v.isoformat()
                elif hasattr(v, "__float__"):
                    clean_r[k] = float(v)
                else:
                    clean_r[k] = v
            serializable_rows.append(clean_r)

        # 3. Record in Provenance Tracker
        if tracker:
            tracker.record_sql(
                query=sanitized_query,
                row_count=len(serializable_rows),
                columns=columns,
                sample_rows=serializable_rows,
                latency_ms=latency_ms,
            )

        return {
            "status": "success",
            "sql": sanitized_query,
            "row_count": len(serializable_rows),
            "columns": columns,
            "data": serializable_rows,
            "latency_ms": round(latency_ms, 2),
            "error": None,
        }

    except SQLSecurityError as e:
        latency_ms = (time.perf_counter() - start_time) * 1000.0
        return {
            "status": "security_violation",
            "sql": query,
            "row_count": 0,
            "columns": [],
            "data": [],
            "latency_ms": round(latency_ms, 2),
            "error": f"Security Guardrail Violation: {e!s}",
        }
    except Exception as e:  # noqa: BLE001
        latency_ms = (time.perf_counter() - start_time) * 1000.0
        return {
            "status": "execution_error",
            "sql": query,
            "row_count": 0,
            "columns": [],
            "data": [],
            "latency_ms": round(latency_ms, 2),
            "error": f"Database Execution Error: {e!s}",
        }
