"""
Schema catalog documents containing table schemas, column types, grains,
and foreign key join paths for the Schema RAG collection.
"""


SCHEMA_DOCUMENTS: list[dict[str, str]] = [
    {
        "id": "schema_sales_mart",
        "table_name": "sales_mart",
        "category": "data_mart",
        "text": (
            "Table: sales_mart\n"
            "Grain: One record per sales_date (daily aggregation of sales).\n"
            "Columns:\n"
            "  - sales_date (DATE): Date of purchase\n"
            "  - total_orders (INT): Count of unique orders placed on that day\n"
            "  - total_items (INT): Total quantity of items sold\n"
            "  - total_customers (INT): Unique customers buying on that day\n"
            "  - unique_products (INT): Number of distinct products sold\n"
            "  - active_sellers (INT): Number of distinct merchants selling\n"
            "  - revenue (DECIMAL(12,2)): Total item price revenue (excluding freight)\n"
            "  - freight_revenue (DECIMAL(12,2)): Total freight charge collected\n"
            "  - total_sales_value (DECIMAL(12,2)): Combined price + freight revenue\n"
            "  - average_order_value (DECIMAL(10,2)): revenue / total_orders\n"
            "  - average_item_value (DECIMAL(10,2)): Average price per item\n"
            "Best used for: Daily revenue trends, order volume timelines, AOV tracking, seasonal sales spikes."
        ),
    },
    {
        "id": "schema_customer_mart",
        "table_name": "customer_mart",
        "category": "data_mart",
        "text": (
            "Table: customer_mart\n"
            "Grain: One record per customer_key.\n"
            "Columns:\n"
            "  - customer_key (BIGINT): Surrogate customer identifier\n"
            "  - total_orders (BIGINT): Total lifetime orders placed by customer\n"
            "  - total_items (BIGINT): Total items bought\n"
            "  - total_revenue (DECIMAL(34,2)): Total revenue generated by customer\n"
            "  - total_freight (DECIMAL(34,2)): Total freight paid by customer\n"
            "  - total_sales_value (DECIMAL(34,2)): Lifetime gross spend\n"
            "  - average_order_value (DECIMAL(13,2)): Customer lifetime AOV\n"
            "  - first_purchase (DATETIME): Timestamp of initial purchase\n"
            "  - last_purchase (DATETIME): Timestamp of most recent purchase\n"
            "  - customer_lifetime_days (INT): DATEDIFF between first and last purchase\n"
            "  - customer_type (VARCHAR(20)): 'One-Time Customer' or 'Repeat Customer'\n"
            "Best used for: Customer repeat buying behavior, lifetime value (LTV), customer segmentation."
        ),
    },
    {
        "id": "schema_rfm_mart",
        "table_name": "rfm_mart",
        "category": "data_mart",
        "text": (
            "Table: rfm_mart\n"
            "Grain: One record per customer_key with NTILE(5) RFM scores.\n"
            "Columns:\n"
            "  - customer_key (BIGINT): Customer identifier\n"
            "  - recency (INT): Days since last purchase relative to analysis date\n"
            "  - frequency (BIGINT): Total order count\n"
            "  - monetary_value (DECIMAL(34,2)): Total spend\n"
            "  - recency_score (INT): Recency quintile (1=oldest, 5=most recent)\n"
            "  - frequency_score (INT): Frequency quintile (1=lowest, 5=highest)\n"
            "  - monetary_score (INT): Monetary quintile (1=lowest, 5=highest)\n"
            "  - rfm_segment (VARCHAR(19)): 'Champions', 'Loyal Customers', 'Potential Loyalists', 'Recent Customers', 'Promising', 'Need Attention', 'At Risk', 'Cant Lose Them', 'Hibernating', 'Lost'\n"
            "Best used for: Marketing campaign targeting, customer churn risk analysis, VIP customer tracking."
        ),
    },
    {
        "id": "schema_delivery_mart",
        "table_name": "delivery_mart",
        "category": "data_mart",
        "text": (
            "Table: delivery_mart\n"
            "Grain: One record per order status.\n"
            "Columns:\n"
            "  - order_status (VARCHAR(20)): 'delivered', 'shipped', 'canceled'\n"
            "  - total_orders (BIGINT): Total orders\n"
            "  - delivered_orders (BIGINT): Count of delivered orders\n"
            "  - average_delivery_days (DECIMAL(13,2)): Actual calendar days from purchase to delivery\n"
            "  - average_delivery_delay_days (DECIMAL(13,2)): Average delay in days\n"
            "  - delayed_items (DECIMAL(23,0)): Total items delivered with delay\n"
            "Best used for: Delivery SLA tracking, courier performance, logistics bottleneck diagnosis."
        ),
    },
    {
        "id": "schema_product_mart",
        "table_name": "product_mart",
        "category": "data_mart",
        "text": (
            "Table: product_mart\n"
            "Grain: One record per product_key.\n"
            "Columns:\n"
            "  - product_key (BIGINT): Product identifier\n"
            "  - items_sold (BIGINT): Total quantity sold\n"
            "  - total_orders (BIGINT): Number of distinct orders containing this product\n"
            "  - unique_customers (BIGINT): Distinct customers buying this product\n"
            "  - unique_sellers (BIGINT): Distinct sellers offering this product\n"
            "  - total_revenue (DECIMAL(34,2)): Total revenue generated\n"
            "  - total_freight (DECIMAL(34,2)): Total freight generated\n"
            "  - total_sales_value (DECIMAL(34,2)): Gross product sales\n"
            "  - average_price (DECIMAL(13,2)): Average selling price\n"
            "Best used for: Product catalog analysis, bestsellers, price band analysis."
        ),
    },
    {
        "id": "schema_seller_mart",
        "table_name": "seller_mart",
        "category": "data_mart",
        "text": (
            "Table: seller_mart\n"
            "Grain: One record per seller_key.\n"
            "Columns:\n"
            "  - seller_key (BIGINT): Seller identifier\n"
            "  - total_orders (BIGINT): Total orders fulfilled\n"
            "  - items_sold (BIGINT): Total items shipped\n"
            "  - unique_products_sold (BIGINT): Distinct SKU count sold by merchant\n"
            "  - total_revenue (DECIMAL(34,2)): Merchant gross sales\n"
            "  - total_freight (DECIMAL(34,2)): Total freight collected\n"
            "  - average_order_value (DECIMAL(13,2)): Merchant AOV\n"
            "Best used for: Merchant ranking, partner management, seller tiering."
        ),
    },
    {
        "id": "schema_fact_sales",
        "table_name": "fact_sales",
        "category": "fact_table",
        "text": (
            "Table: fact_sales\n"
            "Grain: One record per order item.\n"
            "Columns:\n"
            "  - sales_key (BIGINT AUTO_INCREMENT): Primary key\n"
            "  - order_id (VARCHAR(32)), order_item_id (INT)\n"
            "  - customer_key (BIGINT), product_key (BIGINT), seller_key (BIGINT)\n"
            "  - purchase_date_key (INT): Foreign key linking to dim_date (YYYYMMDD)\n"
            "  - price (DECIMAL(12,2)), freight_value (DECIMAL(12,2)), total_item_value (DECIMAL(12,2))\n"
            "  - order_status (VARCHAR(20))\n"
            "  - purchase_timestamp, delivered_date, estimated_delivery_date\n"
            "  - delivery_days (INT), delivery_delay_days (INT), is_delayed (TINYINT: 1=delayed, 0=on-time)\n"
            "Joins:\n"
            "  - JOIN dim_customer ON fact_sales.customer_key = dim_customer.customer_key\n"
            "  - JOIN dim_product ON fact_sales.product_key = dim_product.product_key\n"
            "  - JOIN dim_seller ON fact_sales.seller_key = dim_seller.seller_key"
        ),
    },
    {
        "id": "schema_dim_product",
        "table_name": "dim_product",
        "category": "dimension",
        "text": (
            "Table: dim_product\n"
            "Grain: One record per unique product.\n"
            "Columns:\n"
            "  - product_key (BIGINT): Surrogate product key\n"
            "  - product_id (VARCHAR(32)): Natural product identifier\n"
            "  - category_name (VARCHAR(100)): Original Portuguese category\n"
            "  - category_name_english (VARCHAR(100)): English translated category\n"
            "  - product_weight_g (INT), product_length_cm (DECIMAL(10,2)), product_height_cm (DECIMAL(10,2)), product_width_cm (DECIMAL(10,2))\n"
            "Best used for: Joining with fact_sales or product_mart to slice by category_name_english, weight, or dimensions."
        ),
    },
    {
        "id": "schema_dim_customer",
        "table_name": "dim_customer",
        "category": "dimension",
        "text": (
            "Table: dim_customer\n"
            "Grain: One record per unique customer.\n"
            "Columns:\n"
            "  - customer_key (BIGINT): Surrogate customer key\n"
            "  - customer_id (VARCHAR(32)): Natural customer identifier\n"
            "  - customer_unique_id (VARCHAR(32)): Real person identifier\n"
            "  - customer_zip_code_prefix (INT), customer_city (VARCHAR(64)), customer_state (VARCHAR(2))\n"
            "Best used for: Joining with fact_sales to analyze buyer state (e.g. SP, RJ, MG) and city."
        ),
    },
    {
        "id": "schema_dim_seller",
        "table_name": "dim_seller",
        "category": "dimension",
        "text": (
            "Table: dim_seller\n"
            "Grain: One record per unique merchant.\n"
            "Columns:\n"
            "  - seller_key (BIGINT): Surrogate merchant key\n"
            "  - seller_id (VARCHAR(32)): Natural merchant identifier\n"
            "  - seller_zip_code_prefix (INT), seller_city (VARCHAR(64)), seller_state (VARCHAR(2))\n"
            "Best used for: Merchant location analysis and seller origin logistics."
        ),
    },
]
